{
 "title": "K6 Durations & Checks per Page or Group",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Run",
    "query": "SHOW TAG VALUES WITH KEY = \"Run\""
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Duration per Page",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "http_req_duration",
     "query": "SELECT count(\"value\"), mean(\"value\") as avg, min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 95) as p95 FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/) GROUP BY \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks per Page",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as succes FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 1 GROUP BY \"check\", \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as failed FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 0 GROUP BY \"check\", \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as total FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) GROUP BY \"check\", \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Duration per Group",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "http_req_duration",
     "query": "SELECT count(\"value\"), mean(\"value\") as avg, min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 95) as p95 FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/) GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks per Group",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as succes FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 1 GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as failed FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 0 GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(\"value\") as total FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  }
 ]
}