{
 "title": "K6 Testrun Output",
 "description": "Outputs the K6 test results",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Run",
    "query": "SHOW TAG VALUES WITH KEY = \"Run\""
   }
  ]
 },
 "panels": [
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "checks",
     "query": "SELECT COUNT(value) as succes FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 1 GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(value) as failed FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND value = 0 GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "checks",
     "query": "SELECT COUNT(value) as total FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) GROUP BY \"check\", \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Reqquests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_reqs",
     "query": "SELECT COUNT(\"value\") FROM \"http_reqs\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Reqquests per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_reqs",
     "query": "SELECT COUNT(\"value\")/(31*60) FROM \"http_reqs\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_reqs",
     "query": "SELECT COUNT(\"value\") FROM \"iterations\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "VU's Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "http_reqs",
     "query": "SELECT \"value\" FROM \"vus_max\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "measurement": "data_received",
     "query": "SELECT SUM(\"value\") as data_sent FROM \"data_sent\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "data_received",
     "query": "SELECT SUM(\"value\") as data_received FROM \"data_received\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Group Duration",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"group_duration\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Blocked",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_blocked\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Connecting",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_connecting\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Duration",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Receiving",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_receiving\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Sending",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_sending\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests TLS Handshaking",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_tls_handshaking\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Waiting",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"http_req_waiting\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Iteration Duration",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "measurement": "group_duration",
     "query": "SELECT mean(\"value\") as \"avg\", min(\"value\"), median(\"value\") as med, max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 FROM \"iteration_duration\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  }
 ]
}