{
 "title": "Main",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Run",
    "query": "SHOW TAG VALUES WITH KEY = \"Run\""
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average hits/sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_aspnet_app",
     "select": [
      [
       { "params": [ "Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU (Processor time)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Memory (Available Bytes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed checks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Page counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Duration" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Page duration",
   "type": "graph",
   "description": "Total page duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Duration" }
   ],
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/ AND \"page\" != '') AND $timeFilter GROUP BY time($interval), \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "select tag value" }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Group duration",
   "type": "graph",
   "description": "Total page duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Duration" }
   ],
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "group_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "VUs / CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": ".NET Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes in all heaps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "#_Bytes_in_all_Heaps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 0 heap size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "Gen_0_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 1 heap size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "Gen_1_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 2 heap size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "Gen_2_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Induced GC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "#_Induced_GC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=", "value": "test" }
     ]
    },
    {
     "alias": "Gen 0 Collections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "#_Gen_0_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 1 Collections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "#_Gen_1_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 2 Collections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "#_Gen_2_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "LOH size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "select": [
      [
       { "params": [ "Large_Object_Heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "VUs / Available Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_mem",
     "query": "SELECT \"Available_Bytes\" FROM \"win_mem\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "VUs / Requests duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "VUs / Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "win_aspnet",
     "select": [
      [
       { "params": [ "Requests_Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "measurement": "win_aspnet",
     "select": [
      [
       { "params": [ "Requests_Queued" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\"), count(\"value\"), percentile(\"value\", 95), min(\"value\"), max(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/ AND \"page\" != '') AND $timeFilter GROUP BY \"page\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 99, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\"), count(\"value\"), percentile(\"value\", 95), min(\"value\"), max(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } }
 ]
}