{
 "title": "Pensum",
 "time": { "from": "2020-03-17T16:55:57.270Z", "to": "2020-03-17T16:58:18.176Z" },
 "templating": {
  "list": [
   {
    "name": "Run",
    "query": "SHOW TAG VALUES WITH KEY = \"Run\""
   },
   {
    "name": "Run2",
    "query": "SHOW TAG VALUES WITH KEY = \"Run\""
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average hits/sec run #1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_aspnet_app",
     "query": "SELECT mean(\"Requests_persec\") FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average hits/sec difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_aspnet_app",
     "query": "SELECT max(\"mean\") - min(\"mean\") from (SELECT mean(\"Requests_persec\") FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run$/) ), (SELECT mean(\"Requests_persec\") FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run2$/))",
     "select": [
      [
       { "params": [ "Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time run #1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT max(\"mean\") - min(\"mean\") FROM (SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/)), (SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run2$/))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Group duration",
   "type": "table",
   "description": "Total page duration",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/) OR (\"Run\" =~ /^$Run2$/) GROUP BY \"group\", \"Run\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" },
      { "condition": "AND", "key": "page", "operator": "!=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Average hits/sec run #2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_aspnet_app",
     "query": "SELECT mean(\"Requests_persec\") FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run2$/)",
     "select": [
      [
       { "params": [ "Requests_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time run #1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run2$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Memory run #1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Memory difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT max(\"mean\") - min(\"mean\") FROM (SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"run\" =~ /^$Run$/)), (SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"run\" =~ /^$Run2$/))",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU run #1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT max(\"mean\") - min(\"mean\") FROM (SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run$/)), (SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run2$/))",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Memory run #2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE (\"run\" =~ /^$Run2$/)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU run #2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run2$/)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "failed checks run 1",
     "measurement": "checks",
     "query": "SELECT count(\"value\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"checks\" WHERE (\"Run\" =~ /^$Run$/) AND (\"value\" = 0) AND $timeFilter GROUP BY time($interval) fill(null)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "failed checks run 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"Run\" =~ /^$Run2$/) AND (\"value\" = 0) AND $timeFilter GROUP BY time($interval) fill(null)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed checks per group",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"value\") FROM \"checks\" WHERE ((\"Run\" =~ /^$Run$/) OR (\"Run\" =~ /^$Run2$/)) AND (\"value\" = 0) GROUP BY \"check\", \"group\", \"Run\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Virtual users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Vus run 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" AS \"shift_diff(${Run},${Run2})_ms\" FROM \"vus\" WHERE (\"Run\" =~ /^$Run$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vus run 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"vus\" WHERE (\"Run\" =~ /^$Run2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Duration run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 95) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Duration run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\",95) FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Available Bytes run #1",
     "measurement": "win_mem",
     "query": "SELECT \"Available_Bytes\" AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Available Bytes run #2",
     "measurement": "win_mem",
     "query": "SELECT \"Available_Bytes\" FROM \"win_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU run #1",
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "CPU run #2",
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Hits/sec run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Requests_persec\" AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hits/sec run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Requests_persec\" FROM \"win_aspnet_app\" WHERE (\"run\" =~ /^$Run2$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 80, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT * FROM (SELECT percentile(\"value\", 95), count(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run$/)), (SELECT percentile(\"value\", 95), count(\"value\") FROM \"http_req_duration\" WHERE (\"Run\" =~ /^$Run2$/)) GROUP BY \"name\", \"Run\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  { "title": ".NET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Gen 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Gen 0 heap size run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_0_heap_size\")  AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_0_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 0 Collections run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_0_Collections\")) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Gen 0 heap size run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_0_heap_size\")  FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_0_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 0 Collections run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_0_Collections\")) FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Gen 1 heap size run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_1_heap_size\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_1_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 1 Collections run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_1_Collections\")) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Gen_1_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 1 heap size run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_1_heap_size\") FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_1_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 1 Collections run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_1_Collections\")) FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Gen_1_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Gen 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Gen 2 heap size run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_2_heap_size\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_2_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 2 Collections run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_2_Collections\")) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Gen_2_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "LOH size run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Large_Object_Heap_size\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Large_Object_Heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 2 heap size run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Gen_2_heap_size\") FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Gen_2_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Gen 2 Collections run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"#_Gen_2_Collections\")) FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Gen_2_Collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "LOH size run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"Large_Object_Heap_size\") FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Large_Object_Heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes in all heaps run #1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"#_Bytes_in_all_Heaps\") AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Bytes_in_all_Heaps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Bytes in all heaps run #2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_dotnet_mem",
     "query": "SELECT mean(\"#_Bytes_in_all_Heaps\") FROM \"win_dotnet_mem\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "#_Bytes_in_all_Heaps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests in process",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests Current run #1",
     "measurement": "win_aspnet",
     "query": "SELECT MOVING_AVERAGE(\"Requests_Current\", 5) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_aspnet\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Requests_Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Requests Queued run #1",
     "measurement": "win_aspnet",
     "query": "SELECT MOVING_AVERAGE(\"Requests_Queued\", 5) AS \"shift_diff(${Run},${Run2})_ms\" FROM \"win_aspnet\" WHERE (\"run\" =~ /^$Run$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Requests_Queued" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Requests Current run #2",
     "measurement": "win_aspnet",
     "query": "SELECT MOVING_AVERAGE(\"Requests_Current\", 5) FROM \"win_aspnet\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Requests_Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    },
    {
     "alias": "Requests Queued run #2",
     "measurement": "win_aspnet",
     "query": "SELECT MOVING_AVERAGE(\"Requests_Queued\", 5) FROM \"win_aspnet\" WHERE (\"run\" =~ /^$Run2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Requests_Queued" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$Run$/" }
     ]
    }
   ]
  }
 ]
}